apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kg-builder-backend
  namespace: cognito-ai-dq-dev
  labels:
    app: kg-builder-backend
  annotations:
    haproxy.router.openshift.io/timeout: 300s
spec:
  to:
    kind: Service
    name: kg-builder-backend-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kg-builder-web
  namespace: cognito-ai-dq-dev
  labels:
    app: kg-builder-web
  annotations:
    haproxy.router.openshift.io/timeout: 60s
spec:
  to:
    kind: Service
    name: kg-builder-web-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
